# # Client Dockerfile
# FROM node:14
# WORKDIR /app
# COPY . /app
# RUN npm install
# EXPOSE 3000
# CMD ["npm", "start"]

# FROM nginx:alpine
# COPY . /usr/share/nginx/html

# First stage: Python
FROM python:3.11-slim-buster AS builder
WORKDIR /server
COPY . /server
RUN pip install --no-cache-dir -r requirements.txt

# Second stage: Nginx
FROM nginx:alpine
COPY --from=builder /server /usr/share/nginx/html