# # Client Dockerfile
# FROM node:14
# WORKDIR /app
# COPY . /app
# RUN npm install
# EXPOSE 3000
# CMD ["npm", "start"]

# FROM nginx:alpine
# COPY . /usr/share/nginx/htmle

# First stage: Python
FROM python:3.11-slim-buster AS builder
WORKDIR /server
COPY . /server
RUN apt-get update && apt-get install -y gcc python3-dev
RUN pip install -r requirements.txt

# Second stage: Nginx
FROM nginx:alpine
COPY --from=builder /server /usr/share/nginx/html

EXPOSE 8080