# server/dockerfile
# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster
# Set the working directory in the container
WORKDIR /server
# Copy the current directory contents into the container at /app
COPY . /server
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Define environment variable
ENV NAME World
# Expose port 2001
EXPOSE 2001
# Run app.py when the container launches
CMD ["python3", "python/app.py", "--localhost:2001"]